### ISSUE TITLE
Can't enable module

### ISSUE THREAD

**Issue by chouette-cc** [KenediaDev/Kenedia.BlishHUD#28]
Hello,
When I click on "Enable module" button : nothing append.

Blish HUD v1.2.0
Builds Manager : v1.0.7
Kenedia Directory : empty

logs BlishHUD : 

```
1) Could not load type 'Microsoft.Extensions.DependencyInjection.ServiceCollection' from assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=3.1.26.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

Resulting in: An exception occurred while trying to create an instance of type 'Kenedia.Modules.BuildsManager.BuildsManager'.

Resulting in: Cannot activate part 'Kenedia.Modules.BuildsManager.BuildsManager'.
Element: Kenedia.Modules.BuildsManager.BuildsManager -->  Kenedia.Modules.BuildsManager.BuildsManager -->  AssemblyCatalog (Assembly="Kenedia.Modules.BuildsManager, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null")

Resulting in: Cannot get export 'Kenedia.Modules.BuildsManager.BuildsManager (ContractName="Blish_HUD.Modules.Module")' from part 'Kenedia.Modules.BuildsManager.BuildsManager'.
Element: Kenedia.Modules.BuildsManager.BuildsManager (ContractName="Blish_HUD.Modules.Module") -->  Kenedia.Modules.BuildsManager.BuildsManager -->  AssemblyCatalog (Assembly="Kenedia.Modules.BuildsManager, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null")

Resulting in: Cannot set import 'Blish_HUD.Modules.ModuleManager.ModuleInstance (ContractName="Blish_HUD.Modules.Module")' on part 'Blish_HUD.Modules.ModuleManager'.
Element: Blish_HUD.Modules.ModuleManager.ModuleInstance (ContractName="Blish_HUD.Modules.Module") -->  Blish_HUD.Modules.ModuleManager

   at System.ComponentModel.Composition.CompositionResult.ThrowOnErrors(AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ImportEngine.SatisfyImportsOnce(ComposablePart part)
   at System.ComponentModel.Composition.Hosting.CompositionContainer.SatisfyImportsOnce(ComposablePart part)
   at System.ComponentModel.Composition.AttributedModelServices.SatisfyImportsOnce(ICompositionService compositionService, Object attributedPart)
   at Blish_HUD.Modules.ModuleManager.ComposeModuleFromFileSystemReader(String dllName, ModuleParameters parameters) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\GameServices\Modules\ModuleManager.cs:line 243

10:03:58.4953 +01:00 | INFO  | MysticCrafting.Module.Services.Recurring.IRecurringService | API service 'Player Unlocks' loaded successfully with result: 338 recipes, 1349 skins, 15 legendaries.
10:03:58.8848 +01:00 | INFO  | MysticCrafting.Module.Services.Recurring.IRecurringService | API service 'Wallet' loaded successfully with result: 51 currencies loaded
10:04:32.9763 +01:00 | INFO  | MysticCrafting.Module.Services.Recurring.IRecurringService | API service 'Player Items' loaded successfully with result: 666 materials, 210 bank items, 6 shared inventory items, 11 characters loaded
10:04:33.9844 +01:00 | INFO  | MysticCrafting.Module.Services.Recurring.IRecurringService | API service 'Trading Post' loaded successfully with result: 5685 prices loaded
```

EDIT : Work if downgrade to v1.0.5 --> Enable the module --> update the module --> Restart BlishHUD

**Comment by KenediaDev** [comment]
You need to update your pathing module, it's a conflict between the two modules 😊
