### ISSUE TITLE
BuildsManager: Failed to load some data

### ISSUE THREAD

**Issue by sheklesworth** [KenediaDev/Kenedia.BlishHUD#9]
Not sure if this is the expected behavior since the BuildsManager module is still considered "preview", but since SotO released, this is all I get when I try to open the Builds Manager window:

![image](https://github.com/KenediaDev/Kenedia.BlishHUD/assets/45407631/c16c310c-ca4a-4148-9417-ca7828a9e45b)

I've uninstalled/reinstalled the module, made sure I was running a supported version of BlishHud (v1.1.1), and even deleted the JSON templates containing my old builds back from when the module worked in EoD.

My BlishHud API key has every permission granted, so that's not it. 

There are C# exceptions in the BlishHud logfile, but I've uninstalled/reinstalled the Builds Manager module, so I would hope the data has been updated there. Here's what I'm seeing in the logs.

```
18:49:45.2826 | INFO  | Kenedia.Modules.BuildsManager.BuildsManager | Loading data
18:49:45.6101 | WARN  | Kenedia.Modules.BuildsManager.BuildsManager | Failed to load Professions data.
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path 'Version', line 74267, position 14.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Kenedia.Modules.BuildsManager.Services.ProfessionDataEntry.<LoadAndUpdate>d__0.MoveNext() in C:\BhApps\BhudRequestFor\work\Kenedia.Modules.BuildsManager-fLpGf7Sm\BuildsManager\Services\Data\ProfessionDataEntry.cs:line 33

18:49:45.6101 | WARN  | Kenedia.Modules.BuildsManager.BuildsManager | Failed to load Races data.
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path 'Version', line 1809, position 14.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Kenedia.Modules.BuildsManager.Services.RaceDataEntry.<LoadAndUpdate>d__1.MoveNext() in C:\BhApps\BhudRequestFor\work\Kenedia.Modules.BuildsManager-fLpGf7Sm\BuildsManager\Services\Data\RaceDataEntry.cs:line 37

18:49:45.6101 | WARN  | Kenedia.Modules.BuildsManager.BuildsManager | Failed to load Pets data.
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path 'Version', line 1144, position 14.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Kenedia.Modules.BuildsManager.Services.PetDataEntry.<LoadAndUpdate>d__0.MoveNext() in C:\BhApps\BhudRequestFor\work\Kenedia.Modules.BuildsManager-fLpGf7Sm\BuildsManager\Services\Data\PetDataEntry.cs:line 30
```

My current build: 
![image](https://github.com/KenediaDev/Kenedia.BlishHUD/assets/45407631/874d9e1c-43d9-406a-8d3e-20a80509daf5)

Edit: Attaching Pets.json (renamed as Pets.json.txt to make GitHub happy) from my install since that's one of the files generating an exception. `environment` is misspelled as `enviroment`, but I don't see any syntax errors in the JSON.

[Pets.json.txt](https://github.com/KenediaDev/Kenedia.BlishHUD/files/12710504/Pets.json.txt)

**Comment by KenediaDev** [comment]
You need to delete your data folder. The templates don't have to be
deleted.

Wes Santee ***@***.***> schrieb am Mo., 25. Sept. 2023, 04:02:

**Comment by sheklesworth** [comment]
> You need to delete your data folder. The templates don't have to be deleted.

That fixed it, thanks! I figured deleting and reinstalling the module took care of all that, but I guess the `data` folder is considered user data, not module data? In any case, I'm back in business, thanks again!
